'use strict';

const WORKMODE_ROBOT_IDLE           = 'idle';
const WORKMODE_ROBOT_CLEANING       = 'cleaning';

const WORKMODE_STATION_IDLE         = 'idle';
const WORKMODE_STATION_WASHING      = 'washing';
const WORKMODE_STATION_DRYING       = 'drying';
const WORKMODE_STATION_GOCHARGING   = 'goCharging';
const WORKMODE_STATION_GOWASHING    = 'goWashing';
const WORKMODE_STATION_EMPTYING     = 'emptying';
const WORKMODE_STATION_SPINDRYING   = 'spinDrying';

const CHARGE_STATE_IDLE             = 'idle';
const CHARGE_STATE_CHARGING         = 'charging';




module.exports = Object.freeze({
    WORKMODE_ROBOT_IDLE,
    WORKMODE_ROBOT_CLEANING,
    WORKMODE_STATION_IDLE,
    WORKMODE_STATION_WASHING,
    WORKMODE_STATION_DRYING,
    WORKMODE_STATION_GOCHARGING,
    WORKMODE_STATION_GOWASHING,
    WORKMODE_STATION_EMPTYING,
    WORKMODE_STATION_SPINDRYING,
    CHARGE_STATE_IDLE,
    CHARGE_STATE_CHARGING
})